# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_upload_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.ImageField(default='/home/harshita/SBI_PO/uploadfiles/None/no_img.jpg', upload_to='/home/harshitha/SBI_PO/uploadfiles/')),
            ],
            options={
                'db_table': 'image_upload_form',
                'managed': True,
            },
        ),
    ]
