# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize', '0002_auto_20170217_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_upload',
            old_name='email',
            new_name='EmailAddress',
        ),
        migrations.RenameField(
            model_name='image_upload',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='image_upload',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='image_upload',
            name='LastName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
