# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path_one', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
